{{- if .Values.testPingPod.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.testPingPod.name }}
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - name: {{ .Values.testPingPod.name }}
    image: {{ .Values.testPingPod.image }}
    command: ["sleep", "infinity"] # Keeps the pod running indefinitely
    securityContext:
      runAsUser: {{ .Values.testPingPod.securityContext.runAsUser }}
{{- else }}
{{- end }}