apiVersion: v1
kind: ConfigMap
metadata:
  name: slo-exporter-config
  namespace: "{{ .Values.namespace }}"
  labels:
    app: slo-exporter
data:
  regexp_events_classification.csv: |
    uois,gql_ug,high-fast,".*gql_ug.*"
    uois,gql_forms,high-fast,".*gql_forms.*"
  slo_exporter.yaml: |
    webServerListenAddress: "0.0.0.0:8080"
    # Data processing can be customized by adding modules to the pipeline
    pipeline: ["prometheusIngester", "eventKeyGenerator", "dynamicClassifier", "sloEventProducer", "prometheusExporter"]
    modules:
      prometheusIngester:
        apiUrl: "http://prometheus:9090"
        queryTimeout: 30s
        queries:
          - query: "apollo_gql_processing_seconds_bucket"
            type: histogram_increase
            interval: 30s
            additionalLabels:
              event_type: request_latency
      eventKeyGenerator:
        metadataKeys:
          - instance
      dynamicClassifier:
        regexpMatchesCsvFiles:
          - regexp_events_classification.csv
      sloEventProducer:
        rulesFiles:
          - slo_rules.yaml  # Reference to rules file
      prometheusExporter:
        metricName: "slo_events_total"

  slo_rules.yaml: |
    rules:
      # Availability (success/fail) rules
      - metadata_matcher:
          - key: event_type
            operator: isEqualTo
            value: request_result
        failure_conditions:
          - key: result
            operator: isEqualTo
            value: fail
        additional_metadata:
          slo_type: availability

      # Latency rules
      - slo_matcher:
          class: high-fast
        failure_conditions:
          - operator: numberIsHigherThan
            key: le
            value: 0.1
        additional_metadata:
          slo_type: latency90
        metadata_matcher:  # Use this section directly under slo_matcher
          - key: event_type
            operator: isEqualTo
            value: request_latency

      - slo_matcher:
          class: high-fast
        failure_conditions:
          - operator: numberIsHigherThan
            key: le
            value: 0.25
        additional_metadata:
          slo_type: latency99
        metadata_matcher:
          - key: event_type
            operator: isEqualTo
            value: request_latency

      - slo_matcher:
          class: high-slow
        failure_conditions:
          - operator: numberIsHigherThan
            key: le
            value: 1.0
        additional_metadata:
          slo_type: latency90
        metadata_matcher:
          - key: event_type
            operator: isEqualTo
            value: request_latency

      - slo_matcher:
          class: high-slow
        failure_conditions:
          - operator: numberIsHigherThan
            key: le
            value: 5.0
        additional_metadata:
          slo_type: latency99
        metadata_matcher:
          - key: event_type
            operator: isEqualTo
            value: request_latency