apiVersion: v1
kind: Service
metadata:
  name: slo-exporter
  namespace: "{{ .Values.namespace }}"
spec:
  type: ClusterIP
  ports:
    - name: grpc-logging
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: slo-exporter