{
 "title": "Loki Kubernetes Logs",
 "description": "Logs collected from Kubernetes, stored in Loki",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query", "label": "Search Query" },
   { "name": "namespace", "query": "label_values(namespace)" },
   { "name": "stream", "query": "label_values(stream)" },
   { "name": "container", "query": "label_values(container)" }
  ]
 },
 "panels": [
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", stream=~\"$stream\", container =~\"$container\"} |= \"$query\" [$__interval]))",
     "legendFormat": "Log count"
    }
   ]
  },
  {
   "type": "logs",
   "description": "Logs from services running in Kubernetes",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", stream=~\"$stream\", container =~\"$container\"} |= \"$query\""
    }
   ]
  }
 ]
}
{
 "title": "Service Level Objectives (Class Overview)",
 "tags": [ "SLO" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "SLO_domain",
    "label": "Domain",
    "query": {
     "query": "label_values(slo_domain_slo_class_slo_app:slo_events_total,slo_domain)"
    }
   },
   {
    "name": "SLO_class",
    "label": "SLO Class",
    "query": {
     "query": "label_values(slo_domain_slo_class_slo_app:slo_events_total{slo_domain=\"${SLO_domain}\"},slo_class)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SLI Success Overview",
   "type": "table",
   "description": "Percentage of successful SLI events to all events.",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - job:slo_errors_per_request:ratio_rate30m{slo_domain=\"${SLO_domain}\", slo_class=~\"${SLO_class}\"}) *100"
    }
   ]
  },
  {
   "title": "SLO Class Overview",
   "type": "piechart",
   "description": "Number of services in each SLO class in given domain.",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(slo_class) (count (slo_domain_slo_class_slo_app:slo_events_total{slo_domain=\"${SLO_domain}\"}) by(slo_app,slo_class))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI Success Overview",
   "type": "timeseries",
   "description": "Percentage of successful SLI events to all events.",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - job:slo_errors_per_request:ratio_rate30m{slo_domain=\"${SLO_domain}\", slo_class=~\"${SLO_class}\"}) *100",
     "legendFormat": "{{ .Values.slo_app }}, {{ .Values.slo_type }}"
    }
   ]
  },
  {
   "title": "SLO Overview",
   "type": "table",
   "description": "Overview of Service Level Objectives per SLO class",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 9 },
   "targets": [
    { "expr": "service_level_objective:class" }
   ]
  }
 ]
}
{
 "title": "Service Level Objectives (Service Detail)",
 "tags": [ "SLO" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SLO_domain",
    "label": "Domain",
    "query": {
     "query": "label_values(slo_domain_slo_class_slo_app:slo_events_total,slo_domain)"
    }
   },
   {
    "name": "SLO_app",
    "label": "Service",
    "query": {
     "query": "label_values(slo_domain_slo_class_slo_app:slo_events_total{slo_domain=\"${SLO_domain}\"},slo_app)"
    }
   },
   {
    "name": "SLO_type",
    "label": "SLO Type",
    "query": {
     "query": "label_values(slo_domain_slo_class_slo_app:slo_events_total{slo_domain=\"${SLO_domain}\", slo_app=\"${SLO_app}\"},slo_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "${SLO_app}: ${SLO_type}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "SLO_type" },
  {
   "title": "5m Error Budget [events]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(slo_domain_slo_class_slo_app:slo_events_total{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}[5m]))\n* (1 - (sum(service_level_objective:class + on(slo_class) (0* job:slo_errors_per_request:ratio_rate5m{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"})) / 100))"
    }
   ]
  },
  {
   "title": "5m Fail Count [events]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(slo_domain_slo_class_slo_app:slo_events_total{result=\"fail\",slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}[5m]))"
    }
   ]
  },
  {
   "title": "5m Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "(1 - job:slo_errors_per_request:ratio_rate5m{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}) *100",
     "legendFormat": "Success Ratio"
    },
    {
     "expr": "service_level_objective:class + on(slo_class) (0* job:slo_errors_per_request:ratio_rate5m{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"})",
     "legendFormat": "Service Level Objective"
    }
   ]
  },
  {
   "title": "30m Error Budget [events]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(slo_domain_slo_class_slo_app:slo_events_total{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}[30m]))\n* (1 - (sum(service_level_objective:class + on(slo_class) (0* job:slo_errors_per_request:ratio_rate30m{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"})) / 100))"
    }
   ]
  },
  {
   "title": "30m Fail Count [events]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(slo_domain_slo_class_slo_app:slo_events_total{result=\"fail\",slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}[30m]))"
    }
   ]
  },
  {
   "title": "30m Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "(1 - job:slo_errors_per_request:ratio_rate30m{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}) *100",
     "legendFormat": "Success Ratio"
    },
    {
     "expr": "service_level_objective:class + on(slo_class) (0* job:slo_errors_per_request:ratio_rate30m{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"})",
     "legendFormat": "Service Level Objective"
    }
   ]
  },
  {
   "title": "5m Burn Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(slo_domain_slo_class_slo_app:slo_events_total{result=\"fail\",slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}[5m])) / (\n  sum(increase(slo_domain_slo_class_slo_app:slo_events_total{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}[5m])) * (\n    1 - (sum(service_level_objective:class + on(slo_class)\n    (0* job:slo_errors_per_request:ratio_rate5m{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"})) / 100)\n  )\n)"
    }
   ]
  },
  {
   "title": "30m Burn Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(slo_domain_slo_class_slo_app:slo_events_total{result=\"fail\",slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}[30m])) / (\n  sum(increase(slo_domain_slo_class_slo_app:slo_events_total{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}[30m])) * (\n    1 - (sum(service_level_objective:class + on(slo_class)\n    (0* job:slo_errors_per_request:ratio_rate30m{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"})) / 100)\n  )\n)"
    }
   ]
  }
 ]
}
{
 "title": "Cluster monitoring",
 "description": "Docker monitoring with Prometheus and cAdvisor with node and service selection",
 "tags": [
  "docker",
  "cadvisor",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(container_memory_usage_bytes{image!=\"\"}, job)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(container_memory_usage_bytes{job=~\"$job\", image!=\"\"},service)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(container_memory_usage_bytes{job=~\"$job\", image!=\"\", service=~\"$service\"},instance)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_memory_usage_bytes{job=~\"$job\", image!=\"\", service=~\"$service\", instance=~\"$node\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=~\"$node\",job=~\"$job\",image!=\"\"})"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=~\"$node\",job=~\"$job\",image!=\"\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{instance=~\"$node\",job=~\"$job\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{instance=~\"$node\",job=~\"$job\",image!=\"\"}[$__rate_interval]) * 100) "
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{instance=~\"$node\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{instance=~\"$node\",job=~\"$job\",image!=\"\", service=~\"$service\", container=~\"$container\"}[$__rate_interval]) ) * 100 ",
     "legendFormat": "{{`{{name}}`}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container) (container_memory_usage_bytes{instance=~\"$node\",job=~\"$job\",image!=\"\", service=~\"$service\", container=~\"$container\"})",
     "legendFormat": "{{`{{name}}`}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_network_receive_bytes_total{instance=~\"$node\",job=~\"$job\",image!=\"\", service=~\"$service\", container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "recv {{`{{container}}`}}"
    },
    {
     "expr": "-(sum by (container) (rate(container_network_transmit_bytes_total{instance=~\"$node\",job=~\"$job\",image!=\"\", service=~\"$service\", container=~\"$container\"}[$__rate_interval])))",
     "legendFormat": "trans {{`{{container}}`}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_fs_reads_bytes_total{instance=~\"$node\",job=~\"$job\",image!=\"\", service=~\"$service\", container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "read {{`{{container}}`}}"
    },
    {
     "expr": "-(sum by (container) (rate(container_fs_writes_bytes_total{instance=~\"$node\",job=~\"$job\",image!=\"\", service=~\"$service\", container=~\"$container\"}[$__rate_interval])))",
     "legendFormat": "write {{`{{container}}`}}"
    }
   ]
  }
 ]
}
{
 "title": "Snort IDS/IPS",
 "tags": [ "snort" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "ICMP traffic - logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"monitoring/snort\"} |= `ICMP`"
    }
   ]
  },
  {
   "title": "ICMP traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(rate({container=\"snort\"} |= `ICMP` [$__auto]))"
    }
   ]
  }
 ]
}