apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          imagePullPolicy: Always
          #user: '472'
          env:
            - name: GF_INSTALL_PLUGINS
              value: 'grafana-clock-panel,grafana-simple-json-datasource'
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: dashboards-volume
              mountPath: /var/lib/grafana/dashboards
            - name: provisioning-dsb-volume
              mountPath: /etc/grafana/provisioning/dashboards
            - name: provisioning-ds-volume
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: dashboards-volume
          configMap:
            name: grafana-dashboards
        - name: provisioning-volume
          configMap:
            name: grafana-provisioning
        - name: provisioning-ds-volume
          configMap:
            name: grafana-provisioning-ds
        - name: provisioning-dsb-volume
          configMap:
            name: grafana-provisioning-dsb