apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-dsb
  namespace: monitoring
data:
  main.yaml: |
    apiVersion: 1
    providers:
      - name: "Dashboard provider"
        orgId: 1
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: false
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: true