apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-ds
  namespace: monitoring
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus:9090
        access: proxy
        editable: true
        isDefault: true